# Generated by Django 4.2.17 on 2025-07-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activityApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='registered', max_length=20)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activityApp.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Participant',
                'verbose_name_plural': 'Activity Participants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', 'participation_status'], name='activityPar_activit_fbce5c_idx'), models.Index(fields=['user', 'registration_date'], name='activityPar_user_id_9ca83c_idx')],
                'unique_together': {('activity', 'user')},
            },
        ),
    ]
