# Generated by Django 4.2.17 on 2025-08-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityParticipantApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityparticipant',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='activityparticipant',
            index=models.Index(fields=['activity', 'user', 'participation_status'], name='activityPar_activit_ed37fa_idx'),
        ),
    ]
