# Generated by Django 4.2.17 on 2025-08-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='current_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_participants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
